FROM golang:1.19.3-bullseye as builder


FROM builder as app

WORKDIR /go/src/visionService
COPY . /go/src/visionService

RUN go get ./...

RUN go build src/app/main.go


FROM debian:bookworm-slim

#ENV GIN_MODE=release
#ENV DB_USER="root"
#ENV DB_PASSWORD="mariaDb"
#ENV DB_HOST="172.17.0.2"
#ENV DB_PORT="3306"
#ENV DB_NAME="tub"
#ENV PORT=":8080"

COPY --from=app /go/src/visionService/main /app/main

ENTRYPOINT ["/app/main"]